CREATE TABLE JOBS (JOB_ID int NOT NULL, JOB_TITLE VARCHAR(50)  NOT NULL, MIN_SALARY DECIMAL(10,2)  NOT NULL, MAX_SALARY DECIMAL(10,2)  NOT NULL, CHECK(MAX_SALARY - MIN_SALARY >= 2000), PRIMARY KEY (JOB_ID));

ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);

ALTER TABLE LOCATIONS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);

ALTER TABLE COUNTRIES ADD FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);

ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);

ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

CREATE TABLE JOB_HISTORY (EMPLOYEE_ID int NOT NULL, START_DATE DATE NOT NULL, END_DATE DATE NOT NULL, JOB_ID int NOT NULL, DEPARTMENT_ID int NOT NULL, FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID), FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employees(EMPLOYEE_ID), FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID), CONSTRAINT PRIMARY_KEY_JOB_HOSTORY PRIMARY KEY (EMPLOYEE_ID,START_DATE));

